# -*- coding: utf-8 -*-
"""Dishap_shrestha_2409012_Workshop3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAeRl6eYtj7hY_1bb28Pht7fIjUkg-fA
"""



"""Dishap Shrestha

2409012
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

"""Problem 1 - Sorting:
1. Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the
head of the result.
2. Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
dataset, in that order. Print the head of the result.
3. Create a DataFrame called survived gender that contains the Survived and Sex columns of the
Titanic dataset, in that order.Print the head of the result.
"""

df=pd.read_csv('/content/drive/MyDrive/Concept and Technologies of AI/DataSet/Titanic-Dataset.csv')

fare=pd.DataFrame(df['Fare'])
fare.head()

class_age=pd.DataFrame(df[['Pclass','Age']])
class_age.head()

survived_gender=pd.DataFrame(df[['Survived','Sex']])
survived_gender.head()

"""Subsetting Rows:
1. Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it
to fare gt 100.View the printed result.
2. Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to
first class.View the printed result.
3. Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
is female (Sex is "female"), assigning it to female under 18. View the printed result.
"""

fare_gt_100=df[df['Fare']>100]
fare_gt_100.head()

#2
first_class=df[df['Pclass']==1]
print(first_class.head())

#3
female_under_18=df[(df['Age']<18) & (df['Sex']=='female')]
female_under_18.head()

"""1. Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"
(Southampton), assigning the result to embarked c or s. View the printed result.
2. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
or second class), assigning the result to first second class.View the printed result.
"""

embarked_c_or_s=df[(df['Embarked']=='C') | (df['Embarked']=='S')]
embarked_c_or_s.head()

first_second_class=df[(df['Pclass']==1) | (df['Pclass']==2)]
first_second_class.head()

"""Which passenger had the highest fare paid relative to their age?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per year, containing the fare divided by the age of
the passenger(i.e., Fare/Age).
2. Subset rows where fare per year is higher than 5, assigning this to high fare age.
3. Sort high fare age by descending fare per year, assigning this to high fare age srt.
4. Select only the Name and fare per year columns of high fare age srt and save the result as result.
5. Look at the result.
"""

import pandas as pd

titanic = pd.read_csv('/content/drive/MyDrive/Concept and Technologies of AI/DataSet/Titanic-Dataset.csv')

#1.
titanic['Fare_per_Year'] = titanic.apply(lambda row: row['Fare'] / row['Age'] if row['Age'] > 0 else None, axis=1)

# 2.
high_fare_age = titanic[titanic['Fare_per_Year'] > 5]

# 3.
high_fare_age_srt = high_fare_age.sort_values(by='Fare_per_Year', ascending=False)

# 4.
result = high_fare_age_srt[['Name', 'Fare_per_Year']]

# 5.
print(result)

"""Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their
class?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per class, containing the fare divided by the passenger
class i.e. Fare / Pclass.
2. Subset rows where the passenger is male (Sex is ”male”) and an adult (Age is greater than or equal
to 18), assigning this to adult males.
3. Sort adult males by descending fare per class, assigning this to adult males srt.
4. Select only the Name, Age, and fare per class columns of adult males sr and save the result
as result.
5. Look at the result.



"""

# 1. Add a column fare per class (Fare / Pclass)
titanic['Fare_per_Class'] = titanic['Fare'] / titanic['Pclass']


adult_males = titanic[(titanic['Sex'] == 'male') & (titanic['Age'] >= 18)]
adult_males_srt = adult_males.sort_values(by='Fare_per_Class', ascending=False)
result = adult_males_srt[['Name', 'Age', 'Fare_per_Class']]

print(result)

"""What percent of the total fare revenue came from each passenger class?
To answer the question perform following operation:
1. Calculate the total Fare paid across all passengers in the Titanic dataset.
2. Subset for passengers in first class (Pclass is 1) and calculate their total fare.
3. Do the same for second class (Pclass is 2) and third class (Pclass is 3).
4. Combine the fare totals from first, second, and third classes into a list.
5. Divide the totals for each class by the overall total fare to get the proportion of fare revenue by class.
Based on the dataset Answer the following question:
"""

total_fare = titanic['Fare'].sum()

first_class_fare = titanic[titanic['Pclass'] == 1]['Fare'].sum()
second_class_fare = titanic[titanic['Pclass'] == 2]['Fare'].sum()
third_class_fare = titanic[titanic['Pclass'] == 3]['Fare'].sum()
fare_totals = [first_class_fare, second_class_fare, third_class_fare]


proportions = [fare / total_fare * 100 for fare in fare_totals]

classes = ['First Class', 'Second Class', 'Third Class']
for cls, proportion in zip(classes, proportions):
    print(f"{cls}: {proportion:.2f}% of total fare revenue")

"""What percent of the total number of passengers on the Titanic belonged to each age group
(e.g., child, adult, senior)?
To answer the question perform following operation:
1. Create a new column, age group, that categorizes passengers into "child" (age < 18), "adult" (age
18{64), and "senior" (age 65 and above).
2. Calculate the total number of passengers on the Titanic.
3. Count the number of passengers in each age group.
4. Divide the count of each age group by the total number of passengers to get the proportion of passengers
in each age group.
5. Display the proportion as a percentage.
"""

def categorize_age(age):
    if age < 18:
        return 'child'
    elif age >= 65:
        return 'senior'
    else:
        return 'adult'

titanic['Age_Group'] = titanic['Age'].apply(categorize_age)

total_passengers = len(titanic)

age_group_counts = titanic['Age_Group'].value_counts()

age_group_proportions = (age_group_counts / total_passengers) * 100

print("Percentage of passengers by age group:")
for group, proportion in age_group_proportions.items():
    print(f"{group.capitalize()}: {proportion:.2f}%")